### ISSUE TITLE
ModuleNotFoundError: No module named 'hypermatter'

### ISSUE THREAD

**Issue by whui03** [mgoubran/HippMapp3r#4]
Installing collected packages: tensorflow-gpu, HippMapp3r
  Running setup.py develop for HippMapp3r
Successfully installed HippMapp3r tensorflow-gpu-2.0.0

Then, I tried to confirm that the command line function works, and

 hippmapper

Traceback (most recent call last):
  File "/home/w/anaconda3/envs/hippmapper/bin/hippmapper", line 11, in <module>
    load_entry_point('HippMapp3r', 'console_scripts', 'hippmapper')()
  File "/home/w/anaconda3/envs/hippmapper/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/w/anaconda3/envs/hippmapper/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2687, in load_entry_point
    return ep.load()
  File "/home/w/anaconda3/envs/hippmapper/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2341, in load
    return self.resolve()
  File "/home/w/anaconda3/envs/hippmapper/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2347, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/w/HippMapp3r/hippmapper/cli.py", line 14, in <module>
    from hippmapper.segment import hippmapper
  File "/home/w/HippMapp3r/hippmapper/segment/hippmapper.py", line 16, in <module>
    from hypermatter.deep.predict import run_test_case
ModuleNotFoundError: No module named 'hypermatter'

Thank you!

**Comment by mgoubran** [comment]
Hi @whui03, plz update hippmapper, should fix this problem 

$ source activate hippmapper
$ git pull

**Comment by whui03** [comment]
@mgoubran  Hi, another error occured, I couldn't solve this problem. could you help me? Thank you! 

Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/w/anaconda3/envs/hippmapper/bin/platforms" ...
Cannot load library /home/w/anaconda3/envs/hippmapper/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (/home/w/anaconda3/envs/hippmapper/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/w/anaconda3/lib/libQt5XcbQpa.so.5))
QLibraryPrivate::loadPlugin failed on "/home/w/anaconda3/envs/hippmapper/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /home/w/anaconda3/envs/hippmapper/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (/home/w/anaconda3/envs/hippmapper/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/w/anaconda3/lib/libQt5XcbQpa.so.5))"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Fatal Python error: Aborted










I tried  gedit ~/.bashrc to add path. But there doesn't exist the directory.(/home/w/anaconda3/envs/hippmapper/bin/lib)
 >>qmake -version
 >>QMake version 3.0
 >>Using Qt version 5.6.2 in /home/w/anaconda3/envs/hippmapper/bin/lib

**Comment by pmojiri** [comment]
Hi @whui03, sorry for the late reply. Did you get that error when you run hippmapper gui? Did you get any error during installing hippmapper ( "pip install -e .[hippmapper] ") about PyQt5 installation? It seems the PyQt5 is not installed completely on you virtual environment. try this if you get any error for PyQt5 "pip3 install  pyqt5==5.14" when your environment is activated.
